# Generated by Django 4.1.4 on 2023-01-29 10:02

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_Count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('number', models.CharField(blank=True, max_length=50, null=True)),
                ('ordering', models.IntegerField(default=1)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About_Count',
                'verbose_name_plural': 'About_Count',
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='static/modules/')),
                ('ordering', models.IntegerField(default=1)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Clients',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Company_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='static/modules/')),
                ('banner1', models.ImageField(blank=True, null=True, upload_to='static/modules/')),
                ('banner2', models.ImageField(blank=True, null=True, upload_to='static/modules/')),
                ('address', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('about_image_one', models.ImageField(blank=True, null=True, upload_to='static/modules/')),
                ('about_image_two', models.ImageField(blank=True, null=True, upload_to='static/modules/')),
                ('about_image_three', models.ImageField(blank=True, null=True, upload_to='static/modules/')),
                ('about_image_four', models.ImageField(blank=True, null=True, upload_to='static/modules/')),
                ('about_title', models.CharField(blank=True, max_length=50, null=True)),
                ('about_short_desc', models.TextField(blank=True, max_length=1000, null=True)),
                ('about_leader_name', models.CharField(blank=True, max_length=50, null=True)),
                ('about_leader_designation', models.CharField(blank=True, max_length=50, null=True)),
                ('about_leader_speech', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('about_leader_image', models.ImageField(blank=True, null=True, upload_to='static/modules/')),
                ('about_userarea_image1', models.ImageField(blank=True, null=True, upload_to='static/modules/')),
                ('about_userarea_image2', models.ImageField(blank=True, null=True, upload_to='static/modules/')),
                ('about_count_one_title', models.CharField(blank=True, max_length=50, null=True)),
                ('about_count_one_number', models.CharField(blank=True, max_length=50, null=True)),
                ('about_count_two_title', models.CharField(blank=True, max_length=50, null=True)),
                ('about_count_two_number', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=13)),
                ('message', models.TextField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/modules/')),
                ('link', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
                ('short_desc', models.TextField(blank=True, max_length=100, null=True)),
                ('ordering', models.IntegerField(default=1)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Events',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Exclusive_Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('short_desc', models.TextField(blank=True, max_length=1000, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='static/modules/')),
                ('ordering', models.IntegerField(default=1)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Exclusive_Features',
                'verbose_name_plural': 'Exclusive_Features',
            },
        ),
        migrations.CreateModel(
            name='Home_Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('short_desc', models.TextField(blank=True, max_length=1000, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='static/modules/')),
                ('ordering', models.IntegerField(default=1)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Home_Features',
                'verbose_name_plural': 'Home_Features',
            },
        ),
        migrations.CreateModel(
            name='Home_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('short_desc', models.TextField(blank=True, max_length=1000, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='static/modules/')),
                ('ordering', models.IntegerField(default=1)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Home_Products',
                'verbose_name_plural': 'Home_Products',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('website_link', models.CharField(blank=True, max_length=500, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='static/modules/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/modules/')),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('ordering', models.IntegerField(default=1)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Product',
            },
        ),
        migrations.CreateModel(
            name='Product_QA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, max_length=1000, null=True)),
                ('answer', models.TextField(blank=True, max_length=1000, null=True)),
                ('ordering', models.IntegerField(default=1)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Product_QA',
                'verbose_name_plural': 'Product_QA',
            },
        ),
        migrations.CreateModel(
            name='Service_QA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, max_length=1000, null=True)),
                ('answer', models.TextField(blank=True, max_length=1000, null=True)),
                ('ordering', models.IntegerField(default=1)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service_QA',
                'verbose_name_plural': 'Service_QA',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('ordering', models.IntegerField(default=1)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Services',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Static_Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_features_title1', models.CharField(blank=True, max_length=100, null=True)),
                ('home_features_title2', models.CharField(blank=True, max_length=100, null=True)),
                ('home_products_heading', models.CharField(blank=True, max_length=100, null=True)),
                ('home_products_title', models.CharField(blank=True, max_length=100, null=True)),
                ('service_QA_title', models.CharField(blank=True, max_length=100, null=True)),
                ('service_QA_image', models.ImageField(blank=True, null=True, upload_to='static/modules/')),
                ('product_QA_desc', models.TextField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Static_Files',
                'verbose_name_plural': 'Static_Files',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('place', models.CharField(blank=True, max_length=100, null=True)),
                ('salary', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
                ('Type', models.CharField(blank=True, max_length=100, null=True)),
                ('experience', models.CharField(blank=True, max_length=100, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('ordering', models.IntegerField(default=1)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Vacancy',
                'verbose_name_plural': 'Vacancy',
            },
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo_one', models.ImageField(blank=True, null=True, upload_to='static/modules/')),
                ('photo_two', models.ImageField(blank=True, null=True, upload_to='static/modules/')),
                ('description_two', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('ordering', models.IntegerField(default=1)),
                ('status', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='website.product')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
            },
        ),
    ]
