# Generated by Django 4.1.4 on 2023-01-29 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company_details',
            options={'verbose_name': 'Company_Details', 'verbose_name_plural': 'Company_Details'},
        ),
    ]
