# Generated by Django 4.1.4 on 2023-01-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_company_details_about_leader_speech'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_details',
            name='about_count_one_number',
        ),
        migrations.RemoveField(
            model_name='company_details',
            name='about_count_one_title',
        ),
        migrations.RemoveField(
            model_name='company_details',
            name='about_count_two_number',
        ),
        migrations.RemoveField(
            model_name='company_details',
            name='about_count_two_title',
        ),
        migrations.AlterField(
            model_name='company_details',
            name='address',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='static_files',
            name='home_products_title',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
