# Generated by Django 4.1.4 on 2023-01-30 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_about_count_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='Description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
