# Generated by Django 4.1.4 on 2023-01-30 10:12

import ckeditor.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_services_icon_alter_services_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='Description',
        ),
        migrations.AddField(
            model_name='services',
            name='description',
            field=ckeditor.fields.RichTextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
