# Generated by Django 4.1.4 on 2023-01-30 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_services_description_services_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home_features',
            old_name='icon',
            new_name='image',
        ),
    ]
