# Generated by Django 4.1.4 on 2023-01-31 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_rename_icon_home_features_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_details',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
