# Generated by Django 4.1.4 on 2023-01-31 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_applyjob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='Type',
            new_name='type',
        ),
    ]
