# Generated by Django 4.1.4 on 2023-01-31 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_static_files_product_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='static_files',
            name='product_title',
        ),
    ]
