# Generated by Django 4.1.4 on 2023-01-31 09:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_product_name_remove_modules_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='description_one',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
