# Generated by Django 4.1.4 on 2023-01-31 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_modules_description_one'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_name',
            options={'verbose_name': 'Product_Name', 'verbose_name_plural': 'Product_Name'},
        ),
    ]
