# Generated by Django 4.1.4 on 2023-01-31 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_alter_product_name_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_Name',
            new_name='Products_Name',
        ),
        migrations.RenameField(
            model_name='modules',
            old_name='product_name',
            new_name='products_name',
        ),
    ]
