# Generated by Django 4.1.4 on 2023-01-31 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_rename_product_name_products_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products_Name',
            new_name='P_Name',
        ),
        migrations.AlterModelOptions(
            name='p_name',
            options={'verbose_name': 'Products_Name', 'verbose_name_plural': 'Products_Name'},
        ),
    ]
