# Generated by Django 4.1.4 on 2023-01-31 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_rename_products_name_p_name_alter_p_name_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='P_Name',
            new_name='Products_Name',
        ),
        migrations.RemoveField(
            model_name='modules',
            name='products_name',
        ),
    ]
