# Generated by Django 4.1.4 on 2023-01-31 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_delete_products_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='P_Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('ordering', models.IntegerField(default=1)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Name_Of_Product',
                'verbose_name_plural': 'Name_Of_Product',
            },
        ),
    ]
