# Generated by Django 4.1.4 on 2023-01-31 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_p_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='P_Name',
            new_name='Product_Name',
        ),
        migrations.AlterModelOptions(
            name='product_name',
            options={'verbose_name': 'Product_Name', 'verbose_name_plural': 'Product_Name'},
        ),
        migrations.RenameField(
            model_name='product_name',
            old_name='name',
            new_name='name_with_title',
        ),
        migrations.AddField(
            model_name='modules',
            name='product_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='website.product_name'),
            preserve_default=False,
        ),
    ]
