# Generated by Django 4.1.4 on 2023-01-31 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_rename_p_name_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_name',
            name='bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/modules/'),
        ),
    ]
