# Generated by Django 4.1.4 on 2023-01-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_product_name_bg_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_name',
            name='bg_image',
        ),
        migrations.AddField(
            model_name='modules',
            name='bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/modules/'),
        ),
    ]
