# Generated by Django 4.1.4 on 2023-02-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_remove_product_name_bg_image_modules_bg_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
