# Generated by Django 4.1.4 on 2023-02-07 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_modules_title_alter_modules_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module', to='website.modules'),
        ),
    ]
