# Generated by Django 4.1.4 on 2023-02-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_contact_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modules',
            name='description_one',
        ),
        migrations.AddField(
            model_name='modules',
            name='benifits_eight',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='benifits_five',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='benifits_four',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='benifits_one',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='benifits_seven',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='benifits_six',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='benifits_three',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='benifits_two',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
